apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-journey-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-journey
  template:
    metadata:
      labels:
        app: devops-journey
    spec:
      containers:
      - name: devops-journey-container
        image: ghcr.io/devops-journey-uz/devops-journey-k8s:493ffeb93b5ea324eb6dad6c6ea2d37372f0e2f6
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: ghcr