apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-journey-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-journey
  template:
    metadata:
      labels:
        app: devops-journey
    spec:
      containers:
      - name: devops-journey-container
        image: ghcr.io/devops-journey-uz/devops-journey-k8s:fd87b00b525ff7dcbdeef570656b533f23b80912
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: ghcr