apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-journey-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-journey
  template:
    metadata:
      labels:
        app: devops-journey
    spec:
      containers:
      - name: devops-journey-container
        image: ghcr.io/devops-journey-uz/devops-journey-k8s:7204fba4278c9d8567ad5a0968cca4e1aac15c84
        ports:
        - containerPort: 3000 
      imagePullSecrets:
      - name: ghcr