apiVersion: v1
kind: Service
metadata:
  name: devops-journey-service
spec:
  selector:
    app: devops-journey
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer